(function () {

var words = [
  'day.',
 /*! 'vacation.',
 'city.',
  'life!'
  'week.',
  'wedding.',
  'road trip.',
  'birthday.',
  'night out.',
  'travel.',
  'trip.',
  'work day.',
  'school day.',
  'school trip.',
  'party.',
  'relocation.',
  'festival.',
  '(pride) parade.',
  'friends.',
  'sport event.',
  'tournament.',
  'movie night.',
  'bike trip.',
  'engagement.',
  'home life.',
  'pet.',
  'family.',
  'loved ones.',
  'group.',
  'best friends.',
  'college.',
  'university.',
  'graduation.',
  'promotion.',
  'passions.',
  'events.',
  'nature.',
  'country.',
  'world.',
  'planet.',
  'community.',
  'new born.',
  'kids.',
  'new car.',
  'first paycheck.',
  'cooking.',
  'marathon.',
  'success.',
  'struggles.',
  'anniversaries.',
  'parents.',
  'grandparents.',
  'world.',
  'time off.',
  'shopping.',
  'adventures.',
  'holidays.',
  'freedom.',
  'broken heart.',
  'training.',
  'happiness.',
  */
];

var typed = new Typed('.events strong', {
  strings: words,
  typeSpeed: 40,
  backSpeed: 500,
  fadeOut: false,
  loop: false,
  showCursor: false,
  backDelay: 1500,
  startDelay: 0
});

})();
