(function () {

var words = [
  'day.',
 // 'vacation.',
  'week.',
 // 'wedding.',
 // 'road trip.',
 // 'birthday.',
 // 'night out.',
 // 'travel.',
  'trip.',
 // 'work day.',
 // 'school day.',
 // 'school trip.',
 // 'party.',
 // 'relocation.',
 // 'festival.',
 // '(pride) parade.',
 // 'friends.',
 // 'sport event.',
 // 'tournament.',
 // 'movie night.',
 // 'bike trip.',
 // 'engagement.',
 // 'home life.',
 // 'pet.',
 // 'family.',
 // 'loved ones.',
 // 'group.',
 // 'best friends.',
 // 'college.',
 // 'university.',
 // 'graduation.',
 // 'promotion.',
 // 'passions.',
 // 'events.',
 // 'nature.',
  'city.',
 // 'country.',
 // 'world.',
 // 'planet.',
 // 'community.',
 // 'new born.',
 // 'kids.',
 // 'new car.',
 // 'first paycheck.',
 // 'cooking.',
 // 'marathon.',
 // 'success.',
 // 'struggles.',
 // 'anniversaries.',
 // 'parents.',
 // 'grandparents.',
 // 'world.',
 // 'time off.',
 // 'shopping.',
 // 'adventures.',
 // 'holidays.',
 // 'freedom.',
 // 'broken heart.',
 // 'training.',
 // 'happiness.',
  'life!'
];

var typed = new Typed('.events strong', {
  strings: words,
  typeSpeed: 40,
  backSpeed: 500,
  fadeOut: true,
  loop: true,
  showCursor: false,
  backDelay: 1500,
  startDelay: 500
});

})();
